DROP TABLE IF EXISTS products_in_shops;

DROP TABLE IF EXISTS shops;

DROP TABLE IF EXISTS city;

DROP TABLE IF EXISTS street;

DROP TABLE IF EXISTS number;

DROP TABLE IF EXISTS products;

DROP TABLE IF EXISTS category;

CREATE TABLE IF NOT EXISTS city
(
    id SERIAL PRIMARY KEY,
    name VARCHAR(128) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS street
(
    id SERIAL PRIMARY KEY,
    name VARCHAR(128) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS number
(
    id SERIAL PRIMARY KEY,
    name VARCHAR(128) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS shops
(
    id SERIAL PRIMARY KEY,
    name VARCHAR(128) NOT NULL UNIQUE,
    city_id INT REFERENCES city (id) ON DELETE CASCADE,
    street_id INT REFERENCES street (id) ON DELETE CASCADE,
    number_id INT REFERENCES number (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS category
(
    id SERIAL PRIMARY KEY,
    name VARCHAR(128) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS products
(
    id SERIAL PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    category_id INT REFERENCES category (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS products_in_shops
(
    id SERIAL PRIMARY KEY,
    shop_id INT REFERENCES shops (id) ON DELETE CASCADE,
    product_id INT REFERENCES products (id) ON DELETE CASCADE,
    quantity INT NOT NULL
);